version: '3.8'

services:
  grading-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5434/grading_system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_OPEN_IN_VIEW=false
      - SPRING_SERVER_PORT=8085
      - SPRING_SERVLET_CONTEXT_PATH=/api/v1
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
    ports:
      - '8085:8085'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=grading_system
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5434:5432'
